=== lucbontemps/PoliceGIS/solution items/Config/PoliceGisConfiguration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd" xmlns:mstns="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd" elementFormDefault="qualified" id="PoliceGisConfiguration">
	<xs:annotation>
		<xs:appinfo>
      XSD schema for the configuration of the Police GIS application created by GIM NV Belgium.
    </xs:appinfo>
		<xs:documentation>
      TODO: write documentation
    </xs:documentation>
	</xs:annotation>
	<xs:element name="policeGisConfig" type="PoliceGisConfiguration"/>
	<xs:complexType name="PoliceGisConfiguration">
		<xs:sequence>
			<xs:element name="release" type="ApplicationVersion"/>
			<xs:element name="language" type="xs:string"/>
			<xs:element name="releaseDate" type="xs:date"/>
			<xs:element name="directories" type="DirectorySettings"/>
      <xs:element name ="geocoding" type ="GeocodingSettings"></xs:element>
      <xs:element name ="analysis" type ="AnalysisSettings"></xs:element>
		</xs:sequence>
		<xs:attribute name="schemaVersion" type="VersionNumber"/>
	</xs:complexType>
	<xs:simpleType name="VersionNumber">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d+\.\d+\.d+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ApplicationVersion">
		<xs:sequence>
			<xs:element name="majorVersion" type="xs:int"/>
			<xs:element name="minorVersion" type="xs:int"/>
			<xs:element name="implementationVersion" type="xs:int"/>
			<xs:element name="buildNumber" type="xs:int" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DirectorySettings">
		<xs:sequence>
			<xs:element name="dataFolder" type="FilePath"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GeocodingSettings">
		<xs:sequence>
      <xs:element name="GeocodingColumns" type="GeocodingColumns" />
      <xs:element name="MaximumStreetLength" type="xs:unsignedInt" default="200" minOccurs="0" />
      <!--<xs:element name="workSpace" type="FilePath"/>-->
      <xs:element name="addressNotFoundSelection" type="NonEmptyString" />
      <xs:element name="outputCoordinateSystem" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
  
  
	<xs:complexType name="AnalysisSettings">
		<xs:sequence>
      <xs:element name ="aggregationLevels" type="aggregationLevels"/>
      <xs:element name ="analyseTypes" type="analyseTypes"/>
      <xs:element name="NumberIncidentsField" type="NonEmptyString" />
      <xs:element name="NumberOfClasses" type="xs:short" />
      <xs:element name="StreetIDField" type="xs:string"/>
			<xs:element name="areas">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="area"   minOccurs="1" >
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Name" type="NonEmptyString" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            
            <!--
						<xs:element name="areaID" type="xs:ID"/>
            -->
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<!--<xs:element name="geocodingTable" type="TableSpecification"/>-->
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TableSpecification">
		<xs:sequence>
			<xs:element name="tabFile" type="FilePath"/>
      <xs:element name="mustExist" type="xs:boolean"/>
      <xs:element name="knownColumns" type="ColumnMapping"  />
      <!-- todo: field specification et cetera -->
		</xs:sequence>
	</xs:complexType>

  <xs:complexType name="aggregationLevels">
    <xs:sequence>
      <xs:element name="zone" type="xs:string"/>
      <xs:element name="commune" type="xs:string"/>
      <xs:element name="quarter" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="GeocodingColumns">
    <xs:sequence>
      <xs:element name="AddressPtsMunicipalityField" type="xs:string"/>
      <xs:element name="AddressPtsNumberField" type="xs:string"/>
      <xs:element name="AddressPtsStreetField" type="xs:string"/>
      <xs:element name="AdminBordersNameCol" type="xs:string"/>
      <xs:element name="HectoRouteField" type="xs:string"/>
      <xs:element name="HectoDistanceField" type="xs:string"/>
      <xs:element name="HectoAlternativeNameField" type="xs:string"/>
      <xs:element name="StreetLengthMunicipalityFields" type="PossibleColumns"/>
      <xs:element name="Street1FieldCandidates" type="PossibleColumns"/>
      <xs:element name="Street2FieldCandidates" type="PossibleColumns"/>
      <xs:element name="NumberFieldCandidates" type="PossibleColumns"/>
      <xs:element name="HectoMeterFieldCandidates" type="PossibleColumns"/>
      <xs:element name="MunicipalityFieldCandidates" type="PossibleColumns"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="analyseTypes">
    <xs:sequence>
      <xs:element name="point" type="xs:string"/>
      <xs:element name="street" type="xs:string"/>
      <xs:element name="area" type="xs:string"/>
      <xs:element name="black_points" type="xs:string"/>
      <xs:element name="Controles" type="xs:string"/>
      <xs:element name="crime_series" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="NonEmptyString" >
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:whiteSpace value="preserve"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FilePath">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:whiteSpace value="preserve"/>
		</xs:restriction>
	</xs:simpleType>
  <xs:complexType name="ColumnMapping">
    <xs:sequence >
      <xs:element name="column" type="ColumnSpecification" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>    
  <xs:complexType name="ColumnSpecification">
    <xs:sequence>
      <xs:element name="role" type="NonEmptyString"></xs:element>
      <!-- the names could be a list of columns, which have the same role in the application -->
      <xs:element name="name" type="NonEmptyString" minOccurs="1" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PossibleColumns">
    <xs:sequence>
      <xs:element name="name" type="NonEmptyString" minOccurs="1" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== lucbontemps/PoliceGIS/solution items/Config/PoliceGISConfiguration.xml
<?xml version="1.0" encoding="utf-8"?>
<policeGisConfig xmlns="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd PoliceGisConfiguration.xsd">
  <release>
    <majorVersion>2</majorVersion>
    <minorVersion>3</minorVersion>
    <implementationVersion>1</implementationVersion>
  </release>
  <language>fr</language>
  <releaseDate>2018-11-23</releaseDate>
  <directories>
    <dataFolder>C:\Projects\PolicieGIS\data\PolitieGIS</dataFolder>
  </directories>
  <geocoding>
    <GeocodingColumns>
      <AddressPtsMunicipalityField>Gemeente</AddressPtsMunicipalityField>
      <AddressPtsNumberField>HUISNR</AddressPtsNumberField>
      <AddressPtsStreetField>Name_CRAB</AddressPtsStreetField>
      <AdminBordersNameCol>NAME</AdminBordersNameCol>
      <HectoRouteField>wegnr_ISLP</HectoRouteField>
      <HectoDistanceField>HM</HectoDistanceField>
      <HectoAlternativeNameField></HectoAlternativeNameField>
      <StreetLengthMunicipalityFields>
        <name>gemeente</name>
      </StreetLengthMunicipalityFields>
      <Street1FieldCandidates>
        <name>Rue</name>
        <name>Straat</name>
      </Street1FieldCandidates>
      <Street2FieldCandidates>
        <name>Intersection</name>
        <name>Kruispunt met</name>
      </Street2FieldCandidates>
      <NumberFieldCandidates>
        <name>Nr.</name>
        <name>num</name>
      </NumberFieldCandidates>
      <HectoMeterFieldCandidates>
        <name>Hecto</name>
      </HectoMeterFieldCandidates>
      <MunicipalityFieldCandidates>
        <name>Commune</name>
      </MunicipalityFieldCandidates>
    </GeocodingColumns>
    <MaximumStreetLength>200</MaximumStreetLength>
    <addressNotFoundSelection>Niet_gevonden_incidenten</addressNotFoundSelection>
    <outputCoordinateSystem>Earth Projection 3, 1019, ""m"", 4.3674866667, 90, 49.8333339, 51.1666672333, 150000.01300000001, 5400088.4380000001 Bounds (-128761666.217, -123511577.792) (129061666.243, 134311754.668)</outputCoordinateSystem>
  </geocoding>
  <analysis>
    <aggregationLevels>
      <zone>Zone de police</zone>
      <commune>Commune</commune>
      <quarter>Sous-commune</quarter>
    </aggregationLevels>
    <analyseTypes>
      <point>Par points</point>
      <street>Par rues </street>
      <area>Par regions </area>
      <black_points>Points noirs</black_points>
      <Controles>Controles </Controles>
      <crime_series>Incidents en serie</crime_series>
    </analyseTypes>
    <NumberIncidentsField>Aantal_Incidenten</NumberIncidentsField>
    <NumberOfClasses>5</NumberOfClasses>
    <StreetIDField>streetID</StreetIDField>
    <areas>
      <area>
        <Name>01_PZ NOL</Name>
      </area>
    </areas>
  </analysis>
</policeGisConfig>
